services:
  gpuutje-kopen:
    image: zesstevenacht/gpuutje-kopen:latest
    container_name: gpuutje-kopen-app
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - /mnt/Main/Apps/Gpuutje-kopen:/app/data
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: unless-stopped
    stdin_open: true
    tty: true